### ISSUE TITLE
运行之后，发生报错

### ISSUE THREAD

**Issue by Scivous** [yunxiaoshu/eyeurl#3]
Process Process-2:
Traceback (most recent call last):
  File "E:\Python\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "E:\Python\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "E:\InformationSecurity\渗透测试\6.工具\eyeurl\eyeurl.py", line 49, in reqProcess
    driver = webdriver.Chrome(chrome_options=option)
  File "E:\Python\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    super().__init__(
  File "E:\Python\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 106, in __init__
    super().__init__(
  File "E:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 288, in __init__
    self.start_session(capabilities, browser_profile)
  File "E:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 381, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "E:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "E:\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created exception: Missing or invalid capabilities
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 10.0.19045 x86_64)

**Comment by yunxiaoshu** [comment]
浏览器内核问题，检查一下浏览器版本，下载与之对应的内核版本

**Comment by sec404forbidden** [comment]
师傅，谷歌浏览器内核版本是哪个版本 ，在哪里查看？

**Comment by yunxiaoshu** [comment]
谷歌浏览器设置的关于里
