### ISSUE TITLE
脚本很好用，更新谷歌浏览器就不能用了，脚本支持的谷歌浏览器是哪个版本，谢谢。

### ISSUE THREAD

**Issue by sec404forbidden** [yunxiaoshu/eyeurl#5]
************url探测开始************
Process Process-2:
Traceback (most recent call last):
  File "D:\Python3\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\Python3\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "F:\eyeurl\eyeurl.py", line 49, in reqProcess
    driver = webdriver.Chrome(chrome_options=option)
TypeError: __init__() got an unexpected keyword argument 'chrome_options'
************url探测结束,请耐心等待报表生成~************

报表生成完毕，报表所在位置:D:\eyeurl/result/result_1714273610456305000
去重后，url探测共计：0个,共耗时0秒,感谢使用~

**Comment by yunxiaoshu** [comment]
浏览器内核问题，检查一下浏览器版本，下载与之对应的内核版本

**Comment by sec404forbidden** [comment]
是Chrome/107.0.537.36  这个版本嘛

**Comment by yunxiaoshu** [comment]
可以在浏览器设置版本里查看你的
